- README.md
- inf-ruby.el
This allows the user to add
```lisp
(add-hook 'compilation-filter-hook 'inf-ruby-auto-enter)
```
and automatically enter `inf-ruby` at a breakpoint. Currently it only supports the Pry debug pattern, but could support more if needed.
> Automatically entering inf-ruby on pry

- inf-ruby.el
The `ruby-end-of-defun` function doesn't work on it's own (for me at least), but is called by `end-of-defun` according to it's description:
> Move point to the end of the current defun.
> The defun begins at or after the point.  This function is called
> by `end-of-defun'.
```
def test
|
end
```
*Expected*: Definition is send to irb.
*Actual*: `Scan error: "Containing expression ends prematurely", 14, 14`
> Fix ruby-send-definition

- inf-ruby.el
Many people use single quotes unless interpolating in Ruby projects. 
For gems the function `inf-ruby-console-gem` was failing to match `name` and as a result not requiring `lib/name.rb` on invocation of `irb`. 
References:
- http://guides.rubygems.org/specification-reference/
- http://anti-pattern.com/always-use-double-quoted-strings-in-ruby
> Allow single quoted gemspec name

- inf-ruby.el
When a `.zeus.sock` file is present in the current directory this means
that the project uses [zeus](https://github.com/burke/zeus) and would be
suited to use it to launch a console. Depending on if zeus is installed
globally or for the current project only this might require `bundle
exec` to run.
I think it would be a nice addition as it is already supported by `rake.el` 
for example and makes launching a console so much faster.
> Add support for zeus console

- inf-ruby.el
Adds `ruby-send-line` from #98 with no particular binding.
> Add ruby-send-line function

- README.md
Also changed to defvar instead of defconst, for easier customization.
> added chef-shell prompt to inf-ruby-prompt-format

- inf-ruby.el
This commit allows for auto entering inf-ruby mode in minitest compilation buffers
> Add minitest-compilation-mode to Ruby compilation modes

- inf-ruby.el
There are commands for sending and switching to the process buffer for blocks,
definitions and regions. This commit adds such commands for buffers and lines.
> Add ruby-send-{buffer,line}-and-go commands

- inf-ruby.el
This commit resolves deprecation warnings like below:
>DEPRECATION WARNING: Passing the environment's name as
a regular argument is deprecated and will be removed
in the next Rails version. Please, use the -e option instead.
cf. https://github.com/rails/rails/pull/29358
> Resolve deprecation warnings on inf-ruby-console-rails

- inf-ruby.el
Rails by default show the SQL logging information with ANSI colors [`config.colorize_logging` (default to `true`)](https://guides.rubyonrails.org/configuring.html#rails-general-configuration).
`ansi-color-process-output` is autoloaded, and is also used by other comint modes, for instance `python-inferior-mode`.
> Add `ansi-color-process-output` to comint output functions

- inf-ruby.el
Reverts nonsequitur/inf-ruby#118
Ansi color is already applied in the global value of `comint-output-filter-functions`.
> Revert "Add `ansi-color-process-output` to comint output functions"

- inf-ruby.el
This was discussed previously https://github.com/nonsequitur/inf-ruby/issues/47 ~6 years ago. 24.3 is old enough that we can drop support for it enough imho.
> Replace toggle-read-only-mode with read-only-mode

- inf-ruby.el
Currently, we have the print feature built-in `inf-ruby-mode` that inserts the result of an inferior Ruby evaluation
on the current buffer, but this feature does not provide a similar experience that we might find in the Lisp family
languages. So discussing this [issue](https://github.com/nonsequitur/inf-ruby/issues/148) decided to bring
this feature is closer to the Lisp behavior.
It's just an improvement that we already have on `inf-ruby` but also it seems that is a very common issue of developers that came from the Lisp world or are used to work evaluating pieces of code directly on the Emacs buffer. Bellow you can check for some of those discussions that made me look at that:
- https://www.reddit.com/r/ruby/comments/7w82km/how_to_eval_ruby_buffer_in_emacs_and_put_the/
- …
> [FEAT] Creating evaluation results in an overlay on the current buffer

- inf-ruby.el
Currently, we already have the load ruby file feature, but it needs to provide a
the file that must be loaded on the inferior Ruby process.
Usually, we might want to load the file that we are changing on the current buffer so buy having the possibility to just load the current file without typing anything on the mini-buffer could be very handy.
Well, it was quite simple the implementation we just wrapped the `ruby-load-file` providing the current buffer to it, also we defined some default key bind to active that it was inspired on the Cider mode.
> [FEAT] Create load current ruby file fn and key binding

- inf-ruby.el
Previously we have released a new fn called `ruby-load-current-file` using the `buffer-name` fn to retrieve the current buffer and using it to the internal `ruby-load-file`, but recently I've noticed that it didn't work with nested paths for example: 
- It works to load a file on the root `app/foo.rb` because it gets the buffer name that coincides with the file path.
- It does not work when we try to load `app/bar/foo.rb` because it sends only `foo.rb` to inferior process instead of `bar/foo.rb`
Since usually, we work with nested paths we need to fix that, otherwise, this `ruby-load-current-file` fn will work only to load files based on the root directory. 
Well I do not have such large knowledge with Elisp but looking around I've found the [buffer-file-name](url) that seems appropriate …
> Fix load-current-ruby-file in buffers that are not directly on LOAD_PATH (e.g. in subdirectory)

- inf-ruby.el
We already support running inferior ruby processes over remote connections via TRAMP. But the `ruby-send-*` functions use the full file name when sending code over, which includes the remote path. This renders ruby's code introspection useless because source locations use filenames that ruby cannot understand.
For example, if sending code from a file `/tmp/example.rb` on TRAMP remote `/ssh:remote:`, the ruby source locations end up as
`/ssh:remote:/tmp/example.rb`.
This change makes inf-ruby strip the remote path when sending filenames to the inferior ruby process. For compatibility with Emacs versions older than 26.1, it avoids using `(file-local-name)`.
> Add support for TRAMP to ruby-send-* and ruby-load-file

- inf-ruby.el
In `ruby-print-result-value` it searches for " => " to find the result. That is what irb prints:
```
3.2.2 :001 > 2 + 2
=> 4 
```
But pry doesn't include the leading space:
```
[1] pry(main)> 2 + 2                                                                                    
=> 4
```
I simply removed the leading space from the search pattern and just had it search for "=> ", so it works with pry also
> fix ruby-print-result for pry

- inf-ruby.el
* addresses https://github.com/nonsequitur/inf-ruby/issues/49 by sending as a single line string with newlines escaped, rather than multiple lines which cause duplicate intermediate prompts to be displayed
* addresses https://github.com/nonsequitur/inf-ruby/issues/172 by checking comint-max-line-length and if the line is too long, then it writes to a temporary file, and has ruby read and eval and delete the temporary file rather than using comint-send-string
I made `ruby-send-string` as a public interactive function as python and clojure and lisp modes have it, I don't personally use it interactively with those languages but I sometimes bind a key to `lang-send-string` to send a command to restart a service or whatever other action I'm repeatedly doing.
> fix for duplicate prompt and long lines

- inf-ruby.el
Currently `irb -v` on my system outputs a bunch of warnings to stderr before outputting the version to stdout:
```
$ irb -v
Ignoring argon2-2.3.0 because its extensions are not built. Try: gem pristine argon2 --version 2.3.0
[...]
irb 1.12.0 (2024-03-06)
```
which makes starting `inf-ruby` fail with "if: Irb version unknown: ...". Admittedly I should repair my local ruby installation to get rid of these warnings, but I'd like `inf-ruby` (and `robe`) to work nevertheless.
Ignoring all output but the last line like this fixes it for me. Simply adding `2>/dev/null` works as well, but might create compatibility problems with Windows? In any case, please have a critical look at the elisp in this PR, since I'm not 100% confident in it.
> Ignore warnings in `irb -v` output

- inf-ruby.el
Enable compilation workflow as described in https://github.com/nonsequitur/inf-ruby/issues/184#issuecomment-2098763959
> Enable compilation workflow for ruby-quit
